directory: "~/Music/beet"
plugins: "inline"

item_fields:
  disc_and_track: u'%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)

paths:
  default: "$artist/$album/$disc_and_track - $title"
