directory: "~/Music/beet"
plugins: "inline embedart fetchart"

import:
  move: yes
  languages: en

item_fields:
  disc_and_track: u'%02i-%02i' % (disc, track) if disctotal > 1 else u'%02i' % (track)

paths:
  default: "$albumartist/$album/$disc_and_track - $title"

fetchart:
  auto: yes

embedart:
  auto: yes
