# Taps
tap "puma/puma"

# Brews
brew "bat"
brew "coreutils"
brew "diff-so-fancy"
brew "emojify"
brew "fzf"
brew "git"
brew "heroku/brew/heroku"
brew "neovim"
brew "nodenv"
brew "postgresql", restart_service: true
brew "puma/puma/puma-dev"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "vim"
brew "watson"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

# Casks
cask "appcleaner"
cask "atom"
cask "brave-browser"
cask "dropbox"
cask "firefox"
cask "font-iosevka"
cask "iterm2"
cask "karabiner-elements"
cask "rectangle"
cask "slack"
