# Taps
tap "heroku/brew"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "puma/puma"

# Brews
brew "bat"
brew "cmus"
brew "coreutils"
brew "curl"
brew "diff-so-fancy"
brew "elm"
brew "emojify"
brew "exa"
brew "eye-d3"
brew "fzf"
brew "git"
brew "gh"
brew "gnupg"
brew "heroku/brew/heroku"
brew "imagemagick"
brew "inetutils"
brew "less"
brew "lf"
brew "mailcatcher", restart_service: true
brew "ncdu"
brew "neovim"
brew "nodenv"
brew "openssl"
brew "pass"
brew "postgresql", restart_service: true
brew "pandoc"
brew "puma/puma/puma-dev"
brew "pyenv"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "translate-shell"
brew "tree"
brew "universal-ctags"
brew "vim"
brew "watson"
brew "wget"
brew "yarn"
brew "yt-dlp"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

# Casks
cask "1password6"
cask "appcleaner"
cask "authy"
cask "brave-browser"
cask "dropbox"
cask "firefox"
cask "font-iosevka"
cask "inkscape"
cask "iterm2"
cask "karabiner-elements"
cask "mactex-no-gui"
cask "rectangle"
cask "slack"
cask "vlc"

# Apps from App Store
mas "CopyClip", id: 595191960
mas "Pixelmator", id: 407963104
# mas "The Archive Browser", id: 510232205
