# Taps
tap "puma/puma"

# Brews
brew "bash"
brew "bat"
brew "cmus"
brew "coreutils"
brew "curl"
brew "diff-so-fancy"
brew "elm"
brew "emojify"
brew "eza"
brew "eye-d3"
brew "fzf"
brew "gh"
brew "git"
brew "gnupg"
brew "heroku"
brew "hledger"
brew "imagemagick"
brew "inetutils"
brew "less"
brew "lf"
brew "mailcatcher", restart_service: true
brew "ncdu"
brew "neovim"
brew "nmap"
brew "nodenv"
brew "openssl"
brew "pandoc"
brew "pass"
brew "postgresql@17", restart_service: true
brew "puma/puma/puma-dev"
brew "pyenv"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "rsync"
brew "starship"
brew "stow"
brew "tmux"
brew "translate-shell"
brew "universal-ctags"
brew "vim"
brew "watson"
brew "wget"
brew "yarn"
brew "yt-dlp"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

# Casks
cask "bitwarden"
cask "brave-browser"
cask "cyberduck"
cask "dropbox"
cask "firefox"
cask "font-iosevka"
cask "font-iosevka-aile"
cask "font-iosevka-etoile"
cask "iterm2"
cask "karabiner-elements"
cask "rectangle"
cask "slack"
cask "vlc"

# Apps from App Store
mas "Pixelmator", id: 407963104
